language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn test
before_deploy:
  - npm install -g exp
  - exp login -u $EXP_USERNAME -p $EXP_PASSWORD
deploy:
 provider: script
 script: exp publish
 skip_cleanup: true
 on:
   branch: master
   